"""empty message

Revision ID: 18f02a865259
Revises: 55f3d7b0be6e
Create Date: 2020-04-06 19:21:13.282158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f02a865259'
down_revision = '55f3d7b0be6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('postTime', sa.Date(), nullable=True))
    op.drop_column('news', 'dateTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('dateTime', sa.DATETIME(), nullable=True))
    op.drop_column('news', 'postTime')
    # ### end Alembic commands ###
