"""empty message

Revision ID: 1a3c7044786d
Revises: a9619e440c01
Create Date: 2020-02-11 11:32:42.088027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3c7044786d'
down_revision = 'a9619e440c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unavailableDate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unavailableDate_date'), 'unavailableDate', ['date'], unique=False)
    op.create_index(op.f('ix_unavailableDate_id'), 'unavailableDate', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unavailableDate_id'), table_name='unavailableDate')
    op.drop_index(op.f('ix_unavailableDate_date'), table_name='unavailableDate')
    op.drop_table('unavailableDate')
    # ### end Alembic commands ###
