"""empty message

Revision ID: 33a26326b791
Revises: 1a3c7044786d
Create Date: 2020-02-11 14:15:35.794413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a26326b791'
down_revision = '1a3c7044786d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shiftArrangement', sa.Column('sid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shiftArrangement', 'semester', ['sid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shiftArrangement', type_='foreignkey')
    op.drop_column('shiftArrangement', 'sid')
    # ### end Alembic commands ###
