"""empty message

Revision ID: a853f851f3cb
Revises: 
Create Date: 2020-02-03 17:56:12.152120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a853f851f3cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_id'), 'duty', ['id'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=True)
    op.create_table('userData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userData_email'), 'userData', ['email'], unique=True)
    op.create_index(op.f('ix_userData_id'), 'userData', ['id'], unique=True)
    op.create_index(op.f('ix_userData_name'), 'userData', ['name'], unique=False)
    op.create_index(op.f('ix_userData_role'), 'userData', ['role'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['userData.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=True)
    op.create_table('shiftArrangement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('checkIn', sa.DateTime(), nullable=True),
    sa.Column('checkInState', sa.String(length=10), nullable=True),
    sa.Column('checkOut', sa.DateTime(), nullable=True),
    sa.Column('checkOutState', sa.String(length=10), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('did', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['did'], ['duty.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['userData.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shiftArrangement_date'), 'shiftArrangement', ['date'], unique=False)
    op.create_index(op.f('ix_shiftArrangement_id'), 'shiftArrangement', ['id'], unique=True)
    op.create_table('modifyApplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('did', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['shiftArrangement.id'], ),
    sa.ForeignKeyConstraint(['did'], ['duty.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['userData.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifyApplication_id'), 'modifyApplication', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modifyApplication_id'), table_name='modifyApplication')
    op.drop_table('modifyApplication')
    op.drop_index(op.f('ix_shiftArrangement_id'), table_name='shiftArrangement')
    op.drop_index(op.f('ix_shiftArrangement_date'), table_name='shiftArrangement')
    op.drop_table('shiftArrangement')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_userData_role'), table_name='userData')
    op.drop_index(op.f('ix_userData_name'), table_name='userData')
    op.drop_index(op.f('ix_userData_id'), table_name='userData')
    op.drop_index(op.f('ix_userData_email'), table_name='userData')
    op.drop_table('userData')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_duty_id'), table_name='duty')
    op.drop_table('duty')
    # ### end Alembic commands ###
