"""empty message

Revision ID: a9619e440c01
Revises: ba27ed0e6ea2
Create Date: 2020-02-06 07:52:57.088509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9619e440c01'
down_revision = 'ba27ed0e6ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semester_end_date'), 'semester', ['end_date'], unique=False)
    op.create_index(op.f('ix_semester_id'), 'semester', ['id'], unique=True)
    op.create_index(op.f('ix_semester_start_date'), 'semester', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semester_start_date'), table_name='semester')
    op.drop_index(op.f('ix_semester_id'), table_name='semester')
    op.drop_index(op.f('ix_semester_end_date'), table_name='semester')
    op.drop_table('semester')
    # ### end Alembic commands ###
