"""empty message

Revision ID: ba27ed0e6ea2
Revises: a853f851f3cb
Create Date: 2020-02-04 13:43:50.150318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba27ed0e6ea2'
down_revision = 'a853f851f3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userData', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userData', 'password_hash')
    # ### end Alembic commands ###
