"""empty message

Revision ID: f617ca562366
Revises: 
Create Date: 2020-03-23 18:50:09.850892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f617ca562366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_id'), 'duty', ['id'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semester_end_date'), 'semester', ['end_date'], unique=False)
    op.create_index(op.f('ix_semester_id'), 'semester', ['id'], unique=True)
    op.create_index(op.f('ix_semester_start_date'), 'semester', ['start_date'], unique=False)
    op.create_table('unavailableDate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unavailableDate_date'), 'unavailableDate', ['date'], unique=False)
    op.create_index(op.f('ix_unavailableDate_id'), 'unavailableDate', ['id'], unique=True)
    op.create_table('userData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role_ref', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_ref'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userData_email'), 'userData', ['email'], unique=True)
    op.create_index(op.f('ix_userData_id'), 'userData', ['id'], unique=True)
    op.create_index(op.f('ix_userData_name'), 'userData', ['name'], unique=False)
    op.create_index(op.f('ix_userData_role_ref'), 'userData', ['role_ref'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['userData.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=True)
    op.create_table('shiftArrangement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('checkIn', sa.DateTime(), nullable=True),
    sa.Column('checkInState', sa.String(length=10), nullable=True),
    sa.Column('checkOut', sa.DateTime(), nullable=True),
    sa.Column('checkOutState', sa.String(length=10), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('did', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['did'], ['duty.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['userData.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shiftArrangement_date'), 'shiftArrangement', ['date'], unique=False)
    op.create_index(op.f('ix_shiftArrangement_id'), 'shiftArrangement', ['id'], unique=True)
    op.create_table('modifyApplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('did', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['shiftArrangement.id'], ),
    sa.ForeignKeyConstraint(['did'], ['duty.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['userData.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifyApplication_id'), 'modifyApplication', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modifyApplication_id'), table_name='modifyApplication')
    op.drop_table('modifyApplication')
    op.drop_index(op.f('ix_shiftArrangement_id'), table_name='shiftArrangement')
    op.drop_index(op.f('ix_shiftArrangement_date'), table_name='shiftArrangement')
    op.drop_table('shiftArrangement')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_userData_role_ref'), table_name='userData')
    op.drop_index(op.f('ix_userData_name'), table_name='userData')
    op.drop_index(op.f('ix_userData_id'), table_name='userData')
    op.drop_index(op.f('ix_userData_email'), table_name='userData')
    op.drop_table('userData')
    op.drop_index(op.f('ix_unavailableDate_id'), table_name='unavailableDate')
    op.drop_index(op.f('ix_unavailableDate_date'), table_name='unavailableDate')
    op.drop_table('unavailableDate')
    op.drop_index(op.f('ix_semester_start_date'), table_name='semester')
    op.drop_index(op.f('ix_semester_id'), table_name='semester')
    op.drop_index(op.f('ix_semester_end_date'), table_name='semester')
    op.drop_table('semester')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_duty_id'), table_name='duty')
    op.drop_table('duty')
    # ### end Alembic commands ###
